NewDjango/NewDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from blog import views as blog_views
from django.conf import settings
from django.conf.urls.static import static
from users.forms import MyAuthForm, PasswordResetFormCustom

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', blog_views.home, name='home'),
    path('', include('users.urls',namespace='users')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html', authentication_form=MyAuthForm),
     name='login'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
     auth_views.PasswordResetCompleteView.as_view(
         template_name='users/password_reset_complete.html'
     ),
     name='password_reset_complete'),
    # path('', blog_views.home, name='home'),
    path('about/', blog_views.about, name='about'),
    path('',include('core.urls',namespace='core',)),
    #path('menu/', blog_views.menu, name='menu'),
    path('contact/', blog_views.ContactUs, name='contact'),
    path('', include('payments.urls',namespace='payments',)),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NewDjango/core/urls.py
from django.urls import path
# from .views import(
#         menu,
#         ItemListView,
#         ItemCreateView,
#         add_to_cart,
#         remove_from_cart,
#         remove_single_item_from_cart,
#         OrderSummaryView,
#         filterItems,
#         search,
#         add_review,
#         edit_review,
#         delete_review,
#         detail,
#     )
from .views import *
from . import views

app_name = 'core'

urlpatterns = [
    path('menu/', menu , name='menu'),
    path('filter/', filterItems, name='filter'),
    path('search/', search, name='search'),
    path('chef-item-list/', chefItemList , name='chef-item-list'),
    # path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('product/<slug>', detail, name='product'),
    # path('item/new/', ItemCreateView.as_view(), name='product-create'),
    path('item/new/', create_item, name='product-create'),
    path('chef-list/',chef_list, name='chef-list'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
     path('order-history/', OrderHistoryView.as_view(), name='order-history'),
    path('ordered-food-list/', OrderedFoodListView.as_view(), name='ordered-food-list'),
    path('add-to-cart/<slug>/',add_to_cart, name='add-to-cart'),
    path('set-item-unavailable/<slug>/',set_item_unavailable, name='set-item-unavailable'),
    path('set-item-available/<slug>/',set_item_available, name='set-item-available'),
    path('item_delivered/<slug>/<chef_key>',item_delivered, name='item-delivered'),
    path('item_cooking/<slug>/<chef_key>',item_cooking, name='item-cooking'),
    path('remove-from-cart/<slug>/',remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/',remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('addreview/<slug>/', views.add_review, name='add_review'),
    path('edit_review/<slug>/<review_id>',views.edit_review, name='edit_review'),
    path('delete_review/<slug>/<review_id>',views.delete_review, name='delete_review'),
    path('edit_item/<slug>',views.edit_item, name='edit_item'),
]

NewDjango/users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from blog import views as blog_views
from users.forms import MyAuthForm, PasswordResetFormCustom

app_name = 'users'

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    url(r'^signup/$', views.student_signup, name='signup'),
    url(r'^signupstore/$', views.store_signup, name='signupstore'),

    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html', authentication_form=MyAuthForm),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    url(r'^change-password/$', views.change_password, name='change_password'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html', form_class=PasswordResetFormCustom
         ),
         name='password_reset'),
    url(r'^UserFeedback/$',views.UserFeedback,name='UserFeedback')
    # path('password-reset/done/',
    #      auth_views.PasswordResetDoneView.as_view(
    #          template_name='users/password_reset_done.html'
    #      ),
    #      name='password_reset_done'),
    # path('password-reset-confirm/<uidb64>/<token>/',
    #      auth_views.PasswordResetConfirmView.as_view(
    #          template_name='users/password_reset_confirm.html'
    #      ),
    #      name='password_reset_confirm'),
    # path('password-reset-complete/',
    #      auth_views.PasswordResetCompleteView.as_view(
    #          template_name='users/password_reset_complete.html'
    #      ),
    #      name='password_reset_complete'),

]

NewDjango/blog/models.py
from django.db import models

class ContactUs(models.Model):
    
    
    message = models.TextField()
    name = models.CharField(max_length=100)
    email = models.EmailField()


    def __str__(self):
        return self.name

NewDjango/blog/forms.py
from django import forms
from django.contrib.auth.models import User
from . models import *


class ContactUsForm(forms.ModelForm):

    class Meta():
        model = ContactUs
        fields = ['message', 'name', 'email']

        def __init__(self, *args, **kwargs):
	        super(ContactUsForm, self).__init__(*args, **kwargs)
	        self.fields['message'].widget = forms.TextInput(
	            attrs={ 'placeholder': 'Your message'})
	        self.fields['message'].label = False
	        self.fields['name'].widget = forms.TextInput(
	            attrs={ 'placeholder': 'Your name'})
	        self.fields['name'].label = False
	        self.fields['email'].widget = forms.TextInput(
	            attrs={ 'placeholder': 'Your email'})
	        self.fields['email'].label = False

NewDjango/blog/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.conf import settings
from . forms import *
from core.models import *

def home(request):
    if request.user.is_authenticated:
        if request.user.is_student:
            return render(request, 'blog/home.html')
        else:
            if request.method == 'POST':

                filterAtt = request.POST['filter1']
                if filterAtt:
                    if filterAtt == "veg":
                        filter_qs = Item.objects.filter(is_veg=True, chef = request.user)
                        return render(request, 'blog/chef_home.html',context={'items' : filter_qs})
                    elif filterAtt == "nonveg":
                        filter_qs = Item.objects.filter(is_veg=False, chef = request.user)
                        return render(request, 'core/chef_home.html',context={'items' : filter_qs})


                filterAtt = request.POST['filter2']
                if filterAtt:
                    if filterAtt == "lte100":
                        filter_qs = Item.objects.filter(price__range=(0,100), chef = request.user)
                        return render(request, 'core/chef_home.html',context={'items' : filter_qs})
                    elif filterAtt == "100to200":
                        filter_qs = Item.objects.filter(price__range=(101,199), chef = request.user)
                        return render(request, 'core/chef_home.html',context={'items' : filter_qs})
                    elif filterAtt == "gte200":
                        filter_qs = Item.objects.filter(price__range=(200,1000), chef = request.user)
                        return render(request, 'core/chef_home.html',context={'items' : filter_qs})

                sortAtt = request.POST['sort']
                if sortAtt:
                    if sortAtt == "priceAsc":
                        sorted_qs = Item.objects.filter(chef = request.user).order_by('price')
                        return render(request, 'core/chef_home.html',context={'items' : sorted_qs})
                    elif sortAtt == "priceDesc":
                        sorted_qs = Item.objects.order_by('-price')
                        return render(request, 'core/chef_home.html',context={'items' : sorted_qs})

            return render(request, 'blog/chef_home.html', context={'items' : Item.objects.filter(chef = request.user).all()})


    return render(request, 'blog/home.html')


    

def about(request):
    return render(request, 'blog/aboutus.html')


def menu(request):
    return render(request, 'blog/menu.html')


def ContactUs(request):

    form = ContactUsForm()
    print("Hello")
    if request.method == 'POST':
        print("POST")
        
        form = ContactUsForm(request.POST)

        if form.is_valid():
            form.save(commit=True)

            message1 = request.POST.get('message')
            
            message2 = request.POST.get('name')
            message3 = request.POST.get('email')
            
            message =  'Message : ' + message1 + '\n' + 'Name : ' + message2 + '\n' +  'Email : \t' + message3
            

            send_mail('Contact us Form Filled by the User',
            message,
            settings.EMAIL_HOST_USER,
            ['nikhil.k18@iiits.in'],
            fail_silently=False)

            return home(request)

        else:
            #form = ContactUsForm()
            print("Error Form!")

    else:
        #form = ContactUsForm()
        print ("This must be GET")
    return render(request,'blog/contact.html',{'form':form})

NewDjango/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/form.css' %}">

    {% if title %}
        <title>User Profile - {{ title }}</title>
    {% else %}
        <title>User Profile</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      
        <div class="container">
          <a class="navbar-brand mr-4" href=#>User Profie</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href=#>Home</a>
              <a class="nav-item nav-link" href=#>About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              
            </div>
          </div>
        </div>
     
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3></h3>
            <p class='text-muted'>
              <ul class="list-group">
                
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

NewDjango/blog/templates/blog/chef_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/chef_home.css' %}">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Healthy Meal - Meals</title>
    <script src="https://kit.fontawesome.com/6bea53be50.js" crossorigin="anonymous"></script>
</head>

<body>
    <div class="grid-container1 gc">
        <div class="item1">
            <div class="logo">
                <img src="{% static 'core/images/Asset 64@2x.png' %}">
            </div>
            <div class="user">
                <img src="{{ user.profile.image.url }}" class="userimg">

                <div class="username">
                    {{request.user.username}}
                </div>
            </div>
            <div class="opt">
                <div class="head">Menu</div>

                <a href="{% url 'core:chef-list' %}" class="options">
                    <i class="fas fa-book-reader"></i>
                    <div class="optname"> Top Chefs </div>
                </a>
                <a href="{% url 'home' %}" class="options active">
                    <i class="fas fa-utensils"></i>
                    <div class="optname">My Items</div>
                </a>
                <a href=" {% url 'core:ordered-food-list' %} " class="options">
                    <i class="fas fa-shopping-cart"></i>
                    <div class="optname">Ordered Items</div>
                </a>
                <a href="{% url 'users:profile' %}" class="options">
                    <i class="fas fa-user-alt"></i>
                    <div class="optname">User Account</div>
                </a>
               

                <div class="head">Chefs Arena</div>

                <a href="{% url 'core:product-create' %}" class="options">
                    <i class="fas fa-receipt"></i>
                    <div class="optname">Upload Item</div>
                </a>
                <a href="#" class="options">
                    <i class="fas fa-shopping-basket"></i>
                    <div class="optname">Delivered Items</div>
                </a>
                <a href="{% url 'users:logout' %}" class="options signout">
                    <i class="fas fa-power-off"></i>
                    <div class="optname">Sign Out</div>
                </a>
            </div>
        </div>
        <div class="item2">
            <div class="search_bar">
                <form action="{% url 'core:search' %}">
                    <i class="fas fa-search"></i>
                    <input name="q" value="{{request.GET.q}}"type="text" placeholder="Search..">
                </form>
            </div>
            <br> <br> <br> <br> 
            <!-- Filters veg non veg -->
            <form method="POST" enctype="multipart/form-data">
              {% csrf_token %}
                <div class="nut">
                    <div class="carb">
<!--                         <label class="toggle-control">
                            <input type="checkbox" checked="checked">
                            <span class="control"></span>
                        </label><span>Veg</span> -->
                    </div>
                </div>
        </div>

            </form>

        <div class="item3">
            <div class="left">
                <div class="headline">My Food Item list.</div>
                <!-- <div class="hor_nav">
                    <ul>
                        <li><a href="#">Bread</a></li>
                        <li><a href="#">Soup</a></li>
                        <li><a class="active" href="#">Egg</a></li>
                        <li><a href="#">Paneer</a></li>
                        <li><a href="#">Fruits</a></li>
                        <li><a href="#">Milk Products</a></li>
                        <li><a href="#">Nuts</a></li>
                    </ul>
                </div> -->
            </div>
<!--             <div class="right">
                <div class="filter">
                    <select data-menu>
                        <option selected>Filter</option>
                        <option>Price-low to high</option>
                        <option>Highest Rated</option>
                        <option>Alphabetically</option>
                    </select>
                </div>
            </div> -->
            <div class="right">
                  <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <label for="filters"></label>

                    <select id="filter1" name="filter1" onchange="this.form.submit()">
                      <option selected="selected"> Veg / NonVeg </option>
                      <option value="veg">Veg</option>
                      <option value="nonveg">Non-veg</option>
                    </select>

                    <select id="filter2" name="filter2" onchange="this.form.submit()" > 
                      <option selected="selected"> Price </option>
                      <option value="lte100">below 100</option>
                      <option value="100to200">[100-200]</option>
                      <option value="gte200">above 200</option>
                    </select>

                    <select id="sort" name="sort" onchange="this.form.submit()" > 
                      <option selected="selected"> Sort By </option>
                      <option value="priceAsc">Price (low to high)</option>
                      <option value="priceDesc">Price (high to low)</option>
                    </select>      

                  </form>
            </div>

            <!-- Filters sort by price, rating -->
            
        </div>
        <div class="item4">
            <div class="list">
                {% for object in items %}
                          <!--Item 1-->
                          <div class="food_item">
                              <div class="one">
                                  <i class="fas fa-ellipsis-v"></i>
                                  <i class="fas fa-ellipsis-v"></i>
                              </div>
                              <div class="two">
                                  <img src="{{object.image.url}}">
                              </div>
                              <div class="three">
                                  <div class="upar">
                                      <a href="{{object.get_absolute_url}} " class="name">
                                          {{object.title}}
                                      </a>
                                      <div class="price">
                                          Rs. {{ object.price }}
                                      </div>
                                  </div>
                                  <div class="val">
                                      {{object.calories}} Kcal per portion
                                  </div>
                                  <div class="ing">
                                      <div>
                                          <i class="fas fa-apple-alt"></i>
                                      </div>
                                      <div>
                                          <i class="fas fa-pepper-hot"></i>
                                      </div>
                                  </div>
                                  <div class='card-footer text-center'>
                    {% if object.available %}
                      <a href="{% url 'core:set-item-unavailable' object.slug %}" class="btn btn-success">Unavailable</a>
                      <a href="{% url 'core:edit_item' object.slug %}" class="btn btn-danger">Edit</a>
                    {% else %}
                      <a href="{% url 'core:set-item-available' object.slug %}" class="btn btn-success">Available</a>
                      <a href="{% url 'core:edit_item' object.slug %}" class="btn btn-danger">Edit</a>
                    {% endif %}
                      
                  </div>
                                 
                              </div>
                          </div>
                          <!--Item 1 ends-->
                {% endfor %}
            </div>
        </div>
    </div>
    
    <script type="text/javascript">
        var checkboxes = document.getElementsByTagName('input');

        for (var i=0; i<checkboxes.length; i++)  {
          if (checkboxes[i].type == 'checkbox')   {
            checkboxes[i].checked = false;
          }
        }
    </script>
</body>

</html>

    <!--                 <div class="pro">
                        <label class="toggle-control">
                            <input type="checkbox" checked="checked">
                            <span class="control"></span>
                        </label><span>Protein</span>
                    </div> -->

NewDjango/blog/templates/blog/contact-one.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contact Us</title>
    <link rel="stylesheet" href="{% static 'blog/contact.css' %}">

</head>
<body>

<div class="jumbotron">
    <h1>Contact us</h1>
    <h2>Please Fill the below fields</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>
</div>

</body>
</html>

NewDjango/blog/templates/blog/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/contact.css' %}">
    <title>Healthy Meal - Contact</title>
</head>

<body>
   <div class="firstbg">
       <img src="{% static 'blog/images/Asset 555@2x.png' %}">
   </div>
    <div class="grid-container1 gc">

        <div class="item1">

        </div>
        <div class="item2">
            <div class="logo">
                <img src="{% static 'blog/images/Asset 777@2x.png' %}" class="logo_img">
            </div>
            <div class="nav">
                <ul>
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><a href="{% url 'about' %}">About Us</a></li>
                    <li><a class="active" href="{% url 'contact' %}">Contact Us</a></li>
                    <li><a href="{% url 'core:menu' %}">Meals</a></li>
                </ul>
            </div>
            <div class="sign">
                    {% if user.is_authenticated %}
                        <a href=" {% url 'users:logout' %} ">Logout</a>   
                    {% else %}
                        <a href=" {% url 'users:login' %} ">Login</a>
                    {% endif %}
            </div>
        </div>
        <div class="item3">
            <div class="headline">
                We love to<br> hear your feedback
            </div>
        </div>
        <div class="item4">
            <div class="wrapper centered">
                
                <form method="POST" onsubmit="return false;">
                    {% csrf_token %}
                    <article class="letter">
                    <div class="side">
                        <h1>Contact us</h1>
                        
                        <p>
                            {{form.message}}

                        </p>
                    </div>
                    <div class="side">
                        
                        <p>
                            {{form.name}}
                        </p>
                        <p>
                            {{form.email}}
                        </p>
                        <p>
                            <button id="sendLetter">Send</button>  
                        </p>
                    
                
                    </div>
                    </article>
                

                </form>
            

            
            
        

                <div class="envelope front"></div>
                <div class="envelope back"></div>
            </div>
            <p class="result-message centered">Thank you for your message</p>
        </div>
    </div>


    <script type="text/javascript">
        function addClass() {
            document.body.classList.add("sent");
        }

        sendLetter.addEventListener("click", addClass);
    </script>
</body>

</html>

NewDjango/blog/templates/blog/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/home.css' %}">
    <title>Healthy Meal - Home</title>
</head>

<body>
    <img src="{%static 'blog/images/Asset 66@2x.png' %}" class="firstbg">

    <div class="grid-container1 gc">

        <div class="item1">

            
        </div>
        <div class="item2">
            <div class="logo">
                <img src="{%static 'blog/images/Asset 64@2x.png' %}" class="logo_img">
            </div>
            <div class="nav">
                <ul>
                    <li><a href="{% url 'home' %}" class="active">Home</a></li>
                    <li><a href="{% url 'about' %}">About Us</a></li>
                    <li><a href="{% url 'contact' %} ">Chef</a></li>
                    <li><a href="{% url 'contact' %} ">Contact Us</a></li>
                    <li><a href="{% url 'core:menu' %}">Meals</a></li>

                </ul>
            </div>
            <div class="nav">
                    {% if user.is_authenticated %}
                        <li><a href=" {% url 'users:logout' %} ">Logout</a></li>    
                    {% else %}
                    <div class="sign">
                        <a href=" {% url 'users:login' %} ">Login</a></li>
                    </div>
                    
                    {% endif %}
            </div>
        </div>
        <div class="item3">
            <div class="heading">
                Relish Your Every Meal<br>
                With A Blend Of Nutrients...
            </div>
            <div class="subheading">
                Feeling Hungry?
            </div>
            <div class="button">
                <a href="{% url 'core:menu' %} ">Order Now</a>
            </div>
        </div>
        <div class="item4">
            <img src="{% static 'blog/images/Asset 65@2x.png' %}">
            <img src="{%static  'blog/images/Asset 56@2x.png' %}" class="food">
        </div>
    </div>
</body>

</html>

NewDjango/blog/templates/blog/store_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/home.css' %}">
    <title>Healthy Meal - Home</title>
</head>

<body>
    <img src="{%static 'blog/images/Asset 66@2x.png' %}" class="firstbg">

    <div class="grid-container1 gc">

        <div class="item1">

            
        </div>
        <div class="item2">
            <div class="logo">
                <img src="{%static 'blog/images/Asset 64@2x.png' %}" class="logo_img">
            </div>
            <div class="nav">
                <ul>
                    <li><a class="active" href="{% url 'home' %} ">Home</a></li>
                    <li><a href="{% url 'about' %}">About Us</a></li>
                    <li><a href="{% url 'contact' %} ">Contact Us</a></li>
                    <li><a href="{% url 'core:menu' %}">Meals</a></li>
                </ul>
            </div>
            <div class="nav">
                {% if user.is_authenticated %}
                    <li><a href=" {% url 'users:logout' %} ">Logout</a></li>    
                {% else %}
                <ul>
                    <li><a href=" {% url 'users:login' %} ">Login</a></li>
                    <li><a href=" {% url 'users:signup' %} ">Signup</a></li>
                </ul>
                {% endif %}
            </div>
        </div>
        <div class="item3">
            <div class="heading">
                Relish Your Every Meal<br>
                With A Blend Of Nutrients...
            </div>
            <div class="subheading">
                Feeling Hungry?
            </div>
            <div class="button">
                <a href="{% url 'core:menu' %} ">Order Now</a>
            </div>
        </div>
        <div class="item4">
            <img src="{% static 'blog/images/Asset 65@2x.png' %}">
            <img src="{%static  'blog/images/Asset 56@2x.png' %}" class="food">
        </div>
    </div>
</body>

</html>