NewDjango/NewDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from blog import views as blog_views
from django.conf import settings
from django.conf.urls.static import static
from users.forms import MyAuthForm, PasswordResetFormCustom

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', blog_views.home, name='home'),
    path('', include('users.urls',namespace='users')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html', authentication_form=MyAuthForm),
     name='login'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
     auth_views.PasswordResetCompleteView.as_view(
         template_name='users/password_reset_complete.html'
     ),
     name='password_reset_complete'),
    # path('', blog_views.home, name='home'),
    path('about/', blog_views.about, name='about'),
    path('',include('core.urls',namespace='core',)),
    #path('menu/', blog_views.menu, name='menu'),
    path('contact/', blog_views.ContactUs, name='contact'),
    path('', include('payments.urls',namespace='payments',)),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NewDjango/core/urls.py
from django.urls import path
# from .views import(
#         menu,
#         ItemListView,
#         ItemCreateView,
#         add_to_cart,
#         remove_from_cart,
#         remove_single_item_from_cart,
#         OrderSummaryView,
#         filterItems,
#         search,
#         add_review,
#         edit_review,
#         delete_review,
#         detail,
#     )
from .views import *
from . import views

app_name = 'core'

urlpatterns = [
    path('menu/', menu , name='menu'),
    path('filter/', filterItems, name='filter'),
    path('search/', search, name='search'),
    path('chef-item-list/', chefItemList , name='chef-item-list'),
    # path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('product/<slug>', detail, name='product'),
    # path('item/new/', ItemCreateView.as_view(), name='product-create'),
    path('item/new/', create_item, name='product-create'),
    path('chef-list/',chef_list, name='chef-list'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
     path('order-history/', OrderHistoryView.as_view(), name='order-history'),
    path('ordered-food-list/', OrderedFoodListView.as_view(), name='ordered-food-list'),
    path('add-to-cart/<slug>/',add_to_cart, name='add-to-cart'),
    path('set-item-unavailable/<slug>/',set_item_unavailable, name='set-item-unavailable'),
    path('set-item-available/<slug>/',set_item_available, name='set-item-available'),
    path('item_delivered/<slug>/<chef_key>',item_delivered, name='item-delivered'),
    path('item_cooking/<slug>/<chef_key>',item_cooking, name='item-cooking'),
    path('remove-from-cart/<slug>/',remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/',remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('addreview/<slug>/', views.add_review, name='add_review'),
    path('edit_review/<slug>/<review_id>',views.edit_review, name='edit_review'),
    path('delete_review/<slug>/<review_id>',views.delete_review, name='delete_review'),
    path('edit_item/<slug>',views.edit_item, name='edit_item'),
]

NewDjango/payments/urls.py
from django.urls import path
from .views import initiate_payment, callback

app_name = 'payments'

urlpatterns = [
    path('pay/', initiate_payment, name='pay'),
    path('callback/', callback, name='callback'),
]

NewDjango/users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from blog import views as blog_views
from users.forms import MyAuthForm, PasswordResetFormCustom

app_name = 'users'

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    url(r'^signup/$', views.student_signup, name='signup'),
    url(r'^signupstore/$', views.store_signup, name='signupstore'),

    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html', authentication_form=MyAuthForm),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    url(r'^change-password/$', views.change_password, name='change_password'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html', form_class=PasswordResetFormCustom
         ),
         name='password_reset'),
    url(r'^UserFeedback/$',views.UserFeedback,name='UserFeedback')
    # path('password-reset/done/',
    #      auth_views.PasswordResetDoneView.as_view(
    #          template_name='users/password_reset_done.html'
    #      ),
    #      name='password_reset_done'),
    # path('password-reset-confirm/<uidb64>/<token>/',
    #      auth_views.PasswordResetConfirmView.as_view(
    #          template_name='users/password_reset_confirm.html'
    #      ),
    #      name='password_reset_confirm'),
    # path('password-reset-complete/',
    #      auth_views.PasswordResetCompleteView.as_view(
    #          template_name='users/password_reset_complete.html'
    #      ),
    #      name='password_reset_complete'),

]

NewDjango/core/forms.py
from django import forms
from .models import *

class FilterForm(forms.Form):
	filterAtt = forms.CharField(max_length=100, label='Filter Attribute')

class ReviewForm(forms.ModelForm):
	class Meta:
		model = Review
		fields = ("comment","rating")

class ItemForm(forms.ModelForm):
	class Meta:
		model = Item 
		fields = ("title","price","discount_price","is_veg" ,"description","calories","image")

NewDjango/core/views.py
import requests 
from django.contrib import messages
from django.db.models import Q, Avg
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin 
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.shortcuts import redirect
from .models import *
from django.contrib.auth.models import User 
from users.models import User as AbsUser
from django.views.generic import ListView, View, DetailView, CreateView
from django.utils import timezone
from .forms import *
from users.decorators import *
import logging

deleted_reviews = 0

@login_required
def menu(request):
	if request.method == 'POST':

		filterAtt = request.POST['filter1']
		if filterAtt:
			if filterAtt == "veg":
				filter_qs = Item.objects.filter(is_veg=True, available=True)
				return render(request, 'core/menu.html',context={'items' : filter_qs})
			elif filterAtt == "nonveg":
				filter_qs = Item.objects.filter(is_veg=False, available=True)
				return render(request, 'core/menu.html',context={'items' : filter_qs})


		filterAtt = request.POST['filter2']
		if filterAtt:
			if filterAtt == "lte100":
				filter_qs = Item.objects.filter(price__range=(0,100), available=True)
				return render(request, 'core/menu.html',context={'items' : filter_qs})
			elif filterAtt == "100to200":
				filter_qs = Item.objects.filter(price__range=(101,199), available=True)
				return render(request, 'core/menu.html',context={'items' : filter_qs})
			elif filterAtt == "gte200":
				filter_qs = Item.objects.filter(price__range=(200,1000), available=True)
				return render(request, 'core/menu.html',context={'items' : filter_qs})

		sortAtt = request.POST['sort']
		if sortAtt:
			if sortAtt == "priceAsc":
				sorted_qs = Item.objects.filter(available=True).order_by('price')
				return render(request, 'core/menu.html',context={'items' : sorted_qs})
			elif sortAtt == "priceDesc":
				sorted_qs = Item.objects.filter(available=True).order_by('-price')
				return render(request, 'core/menu.html',context={'items' : sorted_qs})

	return render(request, 'core/menu.html', context={'items' : Item.objects.filter(available=True).all()})

def chefItemList(request):
	if request.method == 'POST':

		filterAtt = request.POST['filter1']
		if filterAtt:
			if filterAtt == "veg":
				filter_qs = Item.objects.filter(is_veg=True, chef = request.user)
				return render(request, 'core/chef_item_list.html',context={'items' : filter_qs})
			elif filterAtt == "nonveg":
				filter_qs = Item.objects.filter(is_veg=False, chef = request.user)
				return render(request, 'core/chef_item_list.html',context={'items' : filter_qs})


		filterAtt = request.POST['filter2']
		if filterAtt:
			if filterAtt == "lte100":
				filter_qs = Item.objects.filter(price__range=(0,100), chef = request.user)
				return render(request, 'core/chef_item_list.html',context={'items' : filter_qs})
			elif filterAtt == "100to200":
				filter_qs = Item.objects.filter(price__range=(101,199), chef = request.user)
				return render(request, 'core/chef_item_list.html',context={'items' : filter_qs})
			elif filterAtt == "gte200":
				filter_qs = Item.objects.filter(price__range=(200,1000), chef = request.user)
				return render(request, 'core/chef_item_list.html',context={'items' : filter_qs})

		sortAtt = request.POST['sort']
		if sortAtt:
			if sortAtt == "priceAsc":
				sorted_qs = Item.objects.filter(chef = request.user).order_by('price')
				return render(request, 'core/chef_item_list.html',context={'items' : sorted_qs})
			elif sortAtt == "priceDesc":
				sorted_qs = Item.objects.order_by('-price')
				return render(request, 'core/chef_item_list.html',context={'items' : sorted_qs})

	return render(request, 'core/chef_item_list.html', context={'items' : Item.objects.filter(chef = request.user).all()})



def search(request):
	template = 'core/menu.html'
	query_set = []
	query = request.GET.get('q')
	queries = query.split(" ")
	for q in queries:
		items=Item.objects.filter(
				Q(title__icontains=q) |
				Q(description__icontains=q)
			).distinct()

		for item in items:
			query_set.append(item)

	return render(request, 'core/menu.html', context={'items': list(set(query_set))})

def chef_list(request):
	chefs = AbsUser.objects.filter(is_store_owner=True)
	return render(request, 'core/chefs.html',context={'chefs':chefs})


@store_required
def create_item(request):
	if request.method == "POST":
		form = ItemForm(request.POST, request.FILES)

		if form.is_valid():
			data = form.save(commit=False)
			data.chef = request.user 
			data.slug = datetime.now().strftime("%c")
			data.save()
			return redirect("core:menu")
	else:
		form = ItemForm()
	return render(request, 'core/item_form.html',{"form":form})


class ItemListView(ListView):
	model = Item
	template_name = 'core/menu.html'
	ordering = ['-price']


class OrderSummaryView(LoginRequiredMixin, View):
	def get(self, *args, **kwargs):
		try:
			order = Order.objects.get(user=self.request.user, ordered=False)
			order1 = Order.objects.get(user=self.request.user, ordered=False).items.filter(user=self.request.user,ordered=False).all()
			order2 = Order.objects.get(user=self.request.user, ordered=False).items.filter(user=self.request.user,ordered=True).all()
			context = {
				'object' : order,
				'object1' : order1,
				'object2' : order2
			}
			return render(self.request, 'core/order_summary.html', context)
		except ObjectDoesNotExist:
			messages.info(self.request, "You do not have an active order")
			return redirect("core:menu")

class OrderHistoryView(LoginRequiredMixin, View):
	def get(self, *args, **kwargs):
		try:
			order = Order.objects.get(user=self.request.user, ordered=False)
			order1 = Order.objects.get(user=self.request.user, ordered=False).items.filter(user=self.request.user,ordered=False).all()
			order2 = Order.objects.get(user=self.request.user, ordered=False).items.filter(user=self.request.user,ordered=True).all()
			context = {
				'object' : order,
				'object1' : order1,
				'object2' : order2
			}
			return render(self.request, 'core/order_history.html', context)
		except ObjectDoesNotExist:
			messages.info(self.request, "You do not have an order History")
			return redirect("core:menu")

class OrderedFoodListView(LoginRequiredMixin, View):
	def get(self, *args, **kwargs):
		try:
			order = OrderedList.objects.get(chef=self.request.user).items.all()
			# order1 = Order.objects.get(user=self.request.user, ordered=False).items.filter(user=self.request.user,ordered=False).all()
			# order2 = Order.objects.get(user=self.request.user, ordered=False).items.filter(user=self.request.user,ordered=True).all()
			context = {
				'object' : order,
				
			}
			return render(self.request, 'core/ordered_food_list.html', context)
		except ObjectDoesNotExist:
			messages.info(self.request, "You do not have an active order")
			return redirect("core:menu")


# class ItemDetailView(DetailView):
# 	model = Item
# 	template_name = 'core/product.html'

def detail(request, slug):
	item = Item.objects.get(slug=slug)
	reviews = Review.objects.filter(item = item).order_by("-date")
	average = reviews.aggregate(Avg("rating"))["rating__avg"]
	if average == None:
		average = 0
	average = round(average,2)
	item.averageRating = average
	context = {
		"item" : item,
		"reviews" : reviews,
		"average" : average,
	}
	return render(request, 'core/product.html', context)


@login_required
def add_to_cart(request, slug):
	item = get_object_or_404(Item, slug=slug)
	order_item, created = OrderItem.objects.get_or_create(item=item, user= request.user, ordered=False)
	order_qs = Order.objects.filter(user=request.user, ordered=False)
	if order_qs.exists():
		order = order_qs[0]
		#check if the order item is in the order
		if order.items.filter(item__slug=item.slug, ordered = False).exists():
			order_item.quantity += 1
			order_item.save()
			messages.info(request, "This item quantity was updated.")
		else:
			messages.info(request, "This item was added to your cart.")
			order.items.add(order_item)
	else:
		ordered_date = timezone.now()
		order = Order.objects.create(user=request.user, ordered_date = ordered_date)
		order.items.add(order_item)
		messages.info(request, "This item was added to your cart.")
	return redirect("core:order-summary")

@login_required
def set_item_unavailable(request, slug):
	item = get_object_or_404(Item, slug=slug)
	item.set_unavailable()
	return redirect("home")

@login_required
def set_item_available(request, slug):
	item = get_object_or_404(Item, slug=slug)
	item.set_available()
	return redirect("home")



@login_required
def remove_from_cart(request, slug):
	item = get_object_or_404(Item, slug=slug)
	order_qs = Order.objects.filter(user=request.user, ordered=False)
	if order_qs.exists():
		order = order_qs[0]
		#check if the order item is in the order
		if order.items.filter(item__slug=item.slug).exists():
			order_item = OrderItem.objects.filter(item=item, user=request.user, ordered=False)[0]
			#order.items.remove(order_item)
			order_item.delete()
			messages.info(request, "This item was removed from your cart.")
			return redirect("core:order-summary")

		else:
			#the given item is not there in the customer's order
			messages.info(request, "This item is not present in your cart.") 
			return redirect("core:product", slug=slug)
	else:
		#show a message saying that the user doesn't have an order
		messages.info(request, "You do not have an active cart")
		return redirect("core:product", slug=slug)
	return redirect("core:product", slug=slug)

@login_required
def remove_single_item_from_cart(request, slug):
	item = get_object_or_404(Item, slug=slug)
	order_qs = Order.objects.filter(user=request.user, ordered=False)
	if order_qs.exists():
		order = order_qs[0]
		#check if the order item is in the order
		if order.items.filter(item__slug=item.slug).exists():

NewDjango/core/templates/core/chef_item_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>Home Page</title>    
</head>
<body>




    <!--Navigation Bar Starts-->
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggle">
        <div class="navbar-nav mr-auto">
          <a class="nav-item nav-link" href="{% url 'core:menu' %}">Home  </a>
          <a class="nav-item nav-link" href="#">About </a>
        </div>
      <div class="collapse navbar-collapse" id="navbarToggle">
        <div class="navbar-nav mr-auto">
          <a href="{% url 'core:menu' %} ">Menu</a>
          <a  href="{% url 'about' %}">About</a>
        </div>
        <!-- Navbar Right Side -->
        <div class="navbar-nav">

          {% if user.is_authenticated %}
                <a  href=" {% url 'users:logout' %} ">Logout   </a>
                <a  href=" {% url 'core:order-summary' %} ">Cart  </a>
                <a  href="{% url 'users:profile' %} ">Profile  </a>
                <a href="{% url 'core:product-create' %}"> Sell</a>

          {% else %}

                <a href=" {% url 'users:login' %} ">Login</a>
                <a href=" filter/{% url 'users:signup' %} ">Register</a>

          {% endif %}

          
        </div>

      </div>

    </div>
    </nav> 
    </header>
    <!--Nav Bar ends -- >
      <!-- onchange="this.form.submit()" -->
    <br> <br> <br> <br> <br> <br>

<!--       <form method="POST">
      {% csrf_token %}
      <label for="filters">Choose a filter:</label>

      <select id="filter1" name="filter1" onchange="this.form.submit()">
      <option selected="selected"> Nutrient </option>
      <option value="C">Carbohydrates</option>
      <option value="P">Proteins</option>
      <option value="F">Fats</option>
       </select>

      <select id="filter2" name="filter2" onchange="this.form.submit()" > 
        <option selected="selected"> Price </option>
        <option value="lte100">below 100</option>
        <option value="100to200">[100-200]</option>
        <option value="gte200">above 200</option>
      </select>

    </form> -->

    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <label for="filters">Choose a filter:</label>

      <select id="filter1" name="filter1" onchange="this.form.submit()">
        <option selected="selected"> Veg / NonVeg </option>
        <option value="veg">Veg</option>
        <option value="nonveg">Non-veg</option>
      </select>

      <select id="filter2" name="filter2" onchange="this.form.submit()" > 
        <option selected="selected"> Price </option>
        <option value="lte100">below 100</option>
        <option value="100to200">[100-200]</option>
        <option value="gte200">above 200</option>
      </select>

      <select id="sort" name="sort" onchange="this.form.submit()" > 
        <option selected="selected"> Sort By </option>
        <option value="priceAsc">Price (low to high)</option>
        <option value="priceDesc">Price (high to low)</option>
      </select>      

    </form>

  <form method="GET" action="{% url 'core:search' %}">
    <input name="q" value="{{request.GET.q}}" placeholder="search for an item">
    <button class="btn btn-success" type="submit">
      Search
    </button>
    
  </form>

<!--       <div>
      <label for="minprice">Min Price</label>
      <input id="minprice" name="minprice" size="5" type="text" />

      <label for="maxprice">Max Price</label>
      <input id="maxprice" name="maxprice" size="5" type="text" />
      <input type="button" id="submit_form" value="Submit">
      </div> -->



 

  <div class="container">

    <div class="row">
      {% for object in items %}
      <div class="col-md-4 col-sm-4 col-lg-4 m-4">
              <div class="card">
                <img src="{{object.image.url}}" class="card-img-top" alt="{{ product.name }}" height="300" width="300">
                      <div class="card-body">
                        <h5 class="card-title"> {{ object.title }}</h5>
                        <a href="{{object.get_absolute_url}} ">View Details</a>
                        <p class="card-text">{{ object.price }}</p>
                        <span class="badge purple mr-1"> {{object.category}} </span>
                      </div>
                  <div class='card-footer text-center'>
                    {% if object.available %}
                      <a href="{% url 'core:set-item-unavailable' object.slug %}" class="btn btn-success">Unavailable</a>
                      <a href="{% url 'core:edit_item' object.slug %}" class="btn btn-danger">Edit</a>
                    {% else %}
                      <a href="{% url 'core:set-item-available' object.slug %}" class="btn btn-success">Available</a>
                      <a href="{% url 'core:edit_item' object.slug %}" class="btn btn-danger">Edit</a>
                    {% endif %}
                      
                  </div>
               </div>
        </div>
      {% endfor %}



  </div>
  </div>

</body>
</html>

NewDjango/core/templates/core/edit_review.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Edit Review</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

  </head>
  <body>

    <div >
        <form action="" method="POST">
                {% csrf_token %}
                {% if error %}
                  <strong style="color: red;"> {{error}} </strong>
                {% endif %}
                <fieldset class="form-group">
                    {{ form }}
                </fieldset>

                <button type="submit" name="button" >Save changes</button>




        </form>

    </div>



  </body>
</html>

NewDjango/core/templates/core/ordered_food_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'core/meal.css' %}">
    <title>Healthy Meal - Meals</title>
    
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <script src="https://kit.fontawesome.com/6bea53be50.js" crossorigin="anonymous"></script>
</head>

<body>
    <div class="grid-container1 gc">
        <div class="item1">
            <div class="logo">
                <img src="{% static 'core/images/Asset 64@2x.png' %}">
            </div>
            <div class="user">
                <img src="{{ user.profile.image.url }}" class="userimg">

                <div class="username">
                    {{request.user.username}}
                </div>
            </div>
            <div class="opt">
                <div class="head">Menu</div>

                <a href="{% url 'core:chef-list' %}" class="options">
                    <i class="fas fa-book-reader"></i>
                    <div class="optname"> Top Chefs </div>
                </a>
                <a href="{% url 'home' %}" class="options">
                    <i class="fas fa-utensils"></i>
                    <div class="optname">My Items</div>
                </a>
                <a href=" {% url 'core:ordered-food-list' %} " class="options active">
                    <i class="fas fa-shopping-cart"></i>
                    <div class="optname">Ordered Items</div>
                </a>
                <a href="{% url 'users:profile' %}" class="options">
                    <i class="fas fa-user-alt"></i>
                    <div class="optname">User Account</div>
                </a>
               

                <div class="head">Chefs Arena</div>

                <a href="{% url 'core:product-create' %}" class="options">
                    <i class="fas fa-receipt"></i>
                    <div class="optname">Upload Item</div>
                </a>
                <a href="#" class="options">
                    <i class="fas fa-shopping-basket"></i>
                    <div class="optname">Delivered Items</div>
                </a>
                <a href="{% url 'users:logout' %}" class="options signout">
                    <i class="fas fa-power-off"></i>
                    <div class="optname">Sign Out</div>
                </a>
            </div>
        </div>
        

            </form>

        <div class="item3">
            <div class="left">
                <div class="headline">Your Order Summary!!</div>
                
            </div>
            
            <!-- Filters sort by price, rating -->
            
        </div>
        <div class="item4">
            <div class="list">
                {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
        {% endfor %}
  {% endif %}
  <div class="container">
    
    <div class="table-responsive text-nowrap">

  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Item title</th>
        <th scope="col">Price</th>
        <th scope="col">Discount Price</th>        
        <th scope="col">Quantity</th>
        <th scope="col">Total Item Price</th>
        <th scope="col">status</th>
        <th scope="col">status</th>

      </tr>
    </thead>
    <tbody>
    {% for order_item in object %}
      
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td> {{order_item.item.title}} </td>
          <td>{{order_item.item.price}}</td>
          <td>{{order_item.item.discount_price}}</td>
          <td>
                  
                  {{ order_item.quantity }}
                  
          </td>
          <td>
            {% if order_item.item.discount_price %}
                  ${{order_item.get_total_discount_item_price}}
                  <span class="badge badge-primary">Saving ${{order_item.get_amount_saved}}</span>
            {% else %}
                  ${{order_item.get_total_item_price}}
            {% endif %}
            <a style="color: red;" href="{% url 'core:remove-from-cart' order_item.item.slug %}">
              <i class="fas fa-trash-alt float-right"></i>
            </a>
          </td>
          <td>{{order_item.status}}</td>
          <td colspan="6">
            <a class="btn btn-primary float-right ml-2" href="{% url 'core:item-delivered' order_item.item.slug order_item.chef_key %}">Delivered</a>
            <a class="btn btn-warning float-right ml-2" href="{% url 'core:item-cooking' order_item.item.slug order_item.chef_key %}">Cooking</a>
           
          </td>
        </tr>
        {% empty %}
        <tr>
          <td colspan="6">Your cart is empty</td>
        </tr>
        <tr>
          <td colspan="6">
              <a class="btn btn-primary float-right" href="{% url 'core:menu' %}">Continue Shopping</a>
          </td>
        </tr>
        
    {% endfor %}
    
    </tbody>
  

</div>
      
  </div> 
  
            </div>
        </div>
    </div>
    
    <script type="text/javascript">
        var checkboxes = document.getElementsByTagName('input');

        for (var i=0; i<checkboxes.length; i++)  {
          if (checkboxes[i].type == 'checkbox')   {
            checkboxes[i].checked = false;
          }
        }
    </script>
</body>

</html>