NewDjango/NewDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from blog import views as blog_views
from django.conf import settings
from django.conf.urls.static import static
from users.forms import MyAuthForm, PasswordResetFormCustom

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', blog_views.home, name='home'),
    path('', include('users.urls',namespace='users')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html', authentication_form=MyAuthForm),
     name='login'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
     auth_views.PasswordResetCompleteView.as_view(
         template_name='users/password_reset_complete.html'
     ),
     name='password_reset_complete'),
    # path('', blog_views.home, name='home'),
    path('about/', blog_views.about, name='about'),
    path('',include('core.urls',namespace='core',)),
    #path('menu/', blog_views.menu, name='menu'),
    path('contact/', blog_views.ContactUs, name='contact'),
    path('', include('payments.urls',namespace='payments',)),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NewDjango/core/urls.py
from django.urls import path
# from .views import(
#         menu,
#         ItemListView,
#         ItemCreateView,
#         add_to_cart,
#         remove_from_cart,
#         remove_single_item_from_cart,
#         OrderSummaryView,
#         filterItems,
#         search,
#         add_review,
#         edit_review,
#         delete_review,
#         detail,
#     )
from .views import *
from . import views

app_name = 'core'

urlpatterns = [
    path('menu/', menu , name='menu'),
    path('filter/', filterItems, name='filter'),
    path('search/', search, name='search'),
    path('chef-item-list/', chefItemList , name='chef-item-list'),
    # path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('product/<slug>', detail, name='product'),
    # path('item/new/', ItemCreateView.as_view(), name='product-create'),
    path('item/new/', create_item, name='product-create'),
    path('chef-list/',chef_list, name='chef-list'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
     path('order-history/', OrderHistoryView.as_view(), name='order-history'),
    path('ordered-food-list/', OrderedFoodListView.as_view(), name='ordered-food-list'),
    path('add-to-cart/<slug>/',add_to_cart, name='add-to-cart'),
    path('set-item-unavailable/<slug>/',set_item_unavailable, name='set-item-unavailable'),
    path('set-item-available/<slug>/',set_item_available, name='set-item-available'),
    path('item_delivered/<slug>/<chef_key>',item_delivered, name='item-delivered'),
    path('item_cooking/<slug>/<chef_key>',item_cooking, name='item-cooking'),
    path('remove-from-cart/<slug>/',remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/',remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('addreview/<slug>/', views.add_review, name='add_review'),
    path('edit_review/<slug>/<review_id>',views.edit_review, name='edit_review'),
    path('delete_review/<slug>/<review_id>',views.delete_review, name='delete_review'),
    path('edit_item/<slug>',views.edit_item, name='edit_item'),
]

NewDjango/users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from blog import views as blog_views
from users.forms import MyAuthForm, PasswordResetFormCustom

app_name = 'users'

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    url(r'^signup/$', views.student_signup, name='signup'),
    url(r'^signupstore/$', views.store_signup, name='signupstore'),

    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html', authentication_form=MyAuthForm),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    url(r'^change-password/$', views.change_password, name='change_password'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html', form_class=PasswordResetFormCustom
         ),
         name='password_reset'),
    url(r'^UserFeedback/$',views.UserFeedback,name='UserFeedback')
    # path('password-reset/done/',
    #      auth_views.PasswordResetDoneView.as_view(
    #          template_name='users/password_reset_done.html'
    #      ),
    #      name='password_reset_done'),
    # path('password-reset-confirm/<uidb64>/<token>/',
    #      auth_views.PasswordResetConfirmView.as_view(
    #          template_name='users/password_reset_confirm.html'
    #      ),
    #      name='password_reset_confirm'),
    # path('password-reset-complete/',
    #      auth_views.PasswordResetCompleteView.as_view(
    #          template_name='users/password_reset_complete.html'
    #      ),
    #      name='password_reset_complete'),

]

NewDjango/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from PIL import Image
from django.conf import settings
from django.utils import timezone


class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_store_owner = models.BooleanField(default=False)
    #
    # class Meta(AbstractUser.Meta):
    #     swappable = 'AUTH_USER_MODEL'


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)


class UserFeedback(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    Feedback = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

NewDjango/users/forms.py
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from .models import User, Profile, UserFeedback
from django import forms
from django.contrib.auth.forms import AuthenticationForm, PasswordResetForm
from django.forms.widgets import PasswordInput, TextInput




class PasswordResetFormCustom(PasswordResetForm):
    class Meta:
        model = User
        fields = ['email']

    def __init__(self, *args, **kwargs):
        super(PasswordResetFormCustom, self).__init__(*args, **kwargs)
        self.fields['email'].widget = forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Email'})
        self.fields['email'].label = False


class PasswordChangeFormNew(PasswordChangeForm):
    class Meta:
        model = User
        fields = ['old_password', 'new_password1', 'new_password2']

    def __init__(self, *args, **kwargs):
        super(PasswordChangeFormNew, self).__init__(*args, **kwargs)
        self.fields['old_password'].widget = forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'Old Password'})
        self.fields['old_password'].label = False
        self.fields['new_password1'].widget = forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'New Password'})
        self.fields['new_password1'].label = False
        self.fields['new_password2'].widget = forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'Confirm Password'})
        self.fields['new_password2'].label = False


class MyAuthForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

    def __init__(self, *args, **kwargs):
        super(MyAuthForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'})
        self.fields['username'].label = False
        self.fields['password'].widget = forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'})
        self.fields['password'].label = False


class SignupForm(UserCreationForm):
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    is_student = False
    is_store_owner = False

    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'First Name'})
                                 )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Last Name'})
    )
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    password1 = forms.CharField(max_length=16, widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password '}))
    password2 = forms.CharField(max_length=16, widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}))

    class Meta:
        model = User

        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']


class UserFeedbackForm(forms.ModelForm):

    class Meta():
        model = UserFeedback
        fields = '__all__'

NewDjango/users/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib import messages

from .decorators import store_required
from .forms import SignupForm, PasswordChangeFormNew, UserUpdateForm, ProfileUpdateForm, UserFeedbackForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from .models import User, Profile
from django.core.mail import EmailMessage
from django.contrib.auth import update_session_auth_hash
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.urls import reverse



def student_signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.is_student = True
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your Healty Meal account.'
            message = render_to_string('users/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')
    else:
        form = SignupForm()
    return render(request, 'users/user_register.html', {'form': form})


def store_signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.is_store_owner = True
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your blog account.'
            message = render_to_string('users/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')
    else:
        form = SignupForm()
    return render(request, 'users/store_register.html', {'form': form})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        # return redirect('home')
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')

def UserFeedback(request):

    form = UserFeedbackForm()

    if request.method == 'POST':
        
        form = UserFeedbackForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return HttpResponse('Your feedback has been recorded..')

        else:
            print("Error Form!")

    else:
        return render(request,'users/UserFeedback.html',{'form':form})


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeFormNew(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('home')
        else:
            return redirect('home')
    else:
        form = PasswordChangeFormNew(user=request.user)

        args = {'form': form}
        return render(request, 'users/change_password.html', args)


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request,'Your account has been updated!')
            return redirect('users:profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'users/profile.html', context)

NewDjango/users/templates/users/UserFeedback.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Store</title>
</head>
<body>
    Hii! This is Store Home Page
</body>
</html>
 -->
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Healthy Meal</title>
    <link rel = "icon" href ="{% static 'blog/images/Asset 18.png' %}" type = "image/x-icon">
    <link rel="stylesheet" href="{% static 'blog/home.css' %}">

  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  </head>
  <body>
  

<div >

<!--   <a href="{% url 'home' %}"> <img class="home" src="{% static 'blog/images/Asset 18.png' %}" alt="home"> </a> -->

</div>


<div  class="navigation">

    <ul >
      <li><a href="{% url 'home' %}">Home</a></li>
      <li><a href="{% url 'core:menu' %}">Menu</a></li>
<!--       <li><a href="{% url 'users:login' %}">Login</a></li>
      <li><a href="{% url 'users:signup' %}">Register</a></li> -->
      {% if user.is_authenticated %}
                <li><a  href=" {% url 'users:logout' %} ">Logout   </a></li>
                <li><a  href=" {% url 'core:order-summary' %} ">Cart  </a></li>
                <li><a  href="{% url 'users:profile' %} ">Profile  </a></li>
                <li><a href="{% url 'core:product-create' %}"> Sell</a></li>

      {% else %}

                <li><a href=" {% url 'users:login' %} ">Login</a></li>
                <li><a href=" filter/{% url 'users:signup' %} ">Register</a></li>

      {% endif %}
    </ul>

</div>

</div>
    <div >
        	    <form class="form" method="POST">
        			{% csrf_token %}
        			{{ form.as_p }}
        			<input type="submit" class="btn btn-primary" value="Submit">
    			</form>
             

</div>

<p class="tagline">Relish your every meal with a blend of nutrients..</p>


<div >
  <img class="rightbase" src="{% static 'blog/images/Asset 20.png' %}" alt="rightbase">
  <img class="greenbase" src="{% static 'blog/images/Asset 19.png' %}" alt="greenbase">
  <img class="dish" src="{% static 'blog/images/Asset 6.png' %}" alt="dish">





  </body>
</html>

NewDjango/users/templates/users/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}
{% endautoescape %}

NewDjango/users/templates/users/change_password.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Change Password</title>
    <link rel="stylesheet" href="{% static 'users/change_password.css' %}">

  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  </head>
  <body>





<div class="image container">

  <img class="posteregg"src="{% static 'users/images/Asset292x.png' %}" alt="login poster">
    <img class="rightbase" src="{% static 'users/images/Asset552x.png' %}" alt="rightbase">
    <img class="greenstem" src="{% static 'users/images/Asset282x.png' %}" alt="greenstem">
    <img class="discount" src="{% static 'users/images/Asset272x.png' %}" alt="discount">
    <img class="discborder" src="{% static 'users/images/Asset262x.png' %}" alt="discborder">

    <img class="fdot" src="{% static 'users/images/Asset232x.png' %}"alt="fdot">
    <img class="sdot" src="{% static 'users/images/Asset242x.png' %}" alt="sdot">
    <img class="tdot" src="{% static 'users/images/Asset252x.png' %}" alt="tdot">

    <img class="ftext" src="{% static 'users/images/Asset402x.png' %}" alt="ftext">
    <img class="stext" src="{% static 'users/images/Asset382x.png' %}" alt="stext">
    <img class="ttext" src="{% static 'users/images/Asset392x.png' %}" alt="ttext">
</div>






<p class="login">Change Password</p>


<div >


        <form class="form"  method="POST">
            {% csrf_token %}

            {{ form.errors}}
            {{ form.old_password}}

            <br>
            {{ form.new_password1}}
            <br>
            {{ form.new_password2 }}

            <br>
            <button type="submit" name="button" >Submit</button>

        </form>
        <br>

</div>










  </body>
</html>

NewDjango/users/templates/users/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'users/login.css' %}">

  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  </head>
  <body>


<img src="{% static 'users/images/Asset302x.png' %}" class="logo">


<div class="image container">

  <img class="posteregg"src="{% static 'users/images/Asset292x.png' %}" alt="login poster">
    <img class="rightbase" src="{% static 'users/images/Asset400.png' %}" alt="rightbase">
</div>



<p class="login">Login</p>


<div >


        <form class="form"  method="POST" action="{% url 'users:login' %}">
            {% csrf_token %}

            <!-- Please display error here but by different means, coz it is disturbing whole UI-->
            <!-- DO not use form.error-->
            {{ form.username}}

            <br>
            {{ form.password }}

            <br>
                 <button type="submit" name="button" class="sub">Login</button>
                 

        </form>

        <img src="{% static 'users/images/Asset 120@2x.png' %}" style="position: absolute;width: 75px;right: 23%;bottom: 30%;">
        <a href="{% url 'users:signup' %}">
             <img src="{% static 'users/images/Asset 119@2x.png' %}" style="position: absolute;width: 130px;right: 14.5%;bottom: 30%;">
         </a> 
        <br>

</div>










  </body>
</html>

NewDjango/users/templates/users/logout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/home.css' %}">
    <title>Healthy Meal - Home</title>
</head>

<body>
    <img src="{%static 'blog/images/Asset 66@2x.png' %}" class="firstbg">

    <div class="grid-container1 gc">

        <div class="item1">

            
        </div>
        <div class="item2">
            <div class="logo">
                <img src="{%static 'blog/images/Asset 64@2x.png' %}" class="logo_img">
            </div>
            <div class="nav">
                <ul>
                    <li><a class="active" href="{% url 'home' %} ">Home</a></li>
                    <li><a href="{% url 'about' %}">About Us</a></li>
                    <li><a href="{% url 'contact' %} ">Contact Us</a></li>
                    <li><a href="{% url 'core:menu' %}">Meals</a></li>
                </ul>
            </div>
            <div class="nav">
                {% if user.is_authenticated %}
                    <li><a href=" {% url 'users:logout' %} ">Logout</a></li>    
                {% else %}
                <ul>
                    <li><a href=" {% url 'users:login' %} ">Login</a></li>
                    <li><a href=" {% url 'users:signup' %} ">Signup</a></li>
                </ul>
                {% endif %}
            </div>
        </div>
        <div class="item3">
            <div class="heading">
                Relish Your Every Meal<br>
                With A Blend Of Nutrients...
            </div>
            <div class="subheading">
                Feeling Hungry?
            </div>
            <div class="button">
                <a href="{% url 'core:menu' %} ">Order Now</a>
            </div>
        </div>
        <div class="item4">
            <img src="{% static 'blog/images/Asset 65@2x.png' %}">
            <img src="{%static  'blog/images/Asset 56@2x.png' %}" class="food">
        </div>
    </div>
</body>

</html>

NewDjango/users/templates/users/password_reset.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Reset Password</title>
    <link rel="stylesheet" href="{% static 'users/password_reset.css' %}">

  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  </head>
  <body>





<div class="image container">

  <img class="posteregg"src="{% static 'users/images/Asset292x.png' %}" alt="login poster">
    <img class="rightbase" src="{% static 'users/images/Asset552x.png' %}" alt="rightbase">
    <img class="greenstem" src="{% static 'users/images/Asset282x.png' %}" alt="greenstem">
    <img class="discount" src="{% static 'users/images/Asset272x.png' %}" alt="discount">
    <img class="discborder" src="{% static 'users/images/Asset262x.png' %}" alt="discborder">

    <img class="fdot" src="{% static 'users/images/Asset232x.png' %}"alt="fdot">
    <img class="sdot" src="{% static 'users/images/Asset242x.png' %}" alt="sdot">
    <img class="tdot" src="{% static 'users/images/Asset252x.png' %}" alt="tdot">

    <img class="ftext" src="{% static 'users/images/Asset402x.png' %}" alt="ftext">
    <img class="stext" src="{% static 'users/images/Asset382x.png' %}" alt="stext">
    <img class="ttext" src="{% static 'users/images/Asset392x.png' %}" alt="ttext">
</div>






<p class="login">Reset Password</p>


<div >


        <form class="form"  method="POST">
            {% csrf_token %}

            {{ form.errors}}
            {{ form.email}}

            <br>


            <br>
                 <button type="submit" name="button" >Submit</button>

        </form>
        <br>

</div>










  </body>
</html>

NewDjango/users/templates/users/password_reset_complete.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="alert alert-info">
        Your password has been set.
    </div>
    <a href="{% url 'login' %}">Sign In Here</a>
{% endblock content %}

NewDjango/users/templates/users/password_reset_confirm.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Reset Password</button>
            </div>
        </form>
    </div>
{% endblock content %}

NewDjango/users/templates/users/password_reset_done.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="alert alert-info">
        An email has been sent with instructions to reset your password
    </div>
{% endblock content %}

NewDjango/users/templates/users/profile.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
      <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Profile Info</legend>
              {{ u_form}}
              {{ p_form}}
          </fieldset>
          <div class="form-group">
              <button class="btn btn-outline-info" type="submit">Update</button>
          </div>
      </form>
    </div>
{% endblock content %}

NewDjango/users/templates/users/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Register</title>
    <link rel="stylesheet" href="{% static 'users/register.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">



  </head>
  <body>

<div >
  <img class="leftdecoration" src="{% static 'users/images/Asset212x.png' %}" alt="leftdecoration">
  <img src="" alt="">

</div>






    <div >
        <form class="form"   method="POST">
                {% csrf_token %}
                {{ form.password2.errors }}
                {{ form.password1.errors }}
                {{ form.username.errors }}
                {{ form.first_name }}
                {{ form.last_name }}
                <br>
                {{ form.email }}
                <br>
                {{ form.username }}
                <br>
                {{ form.password1 }}
                <br>
                {{ form.password2}}


                <br>
                <button type="submit" name="button" >Register</button>




        </form>

    </div>



  </body>
</html>

NewDjango/users/templates/users/store_register.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Register</title>
    <link rel="stylesheet" href="{% static 'users/register.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">



  </head>
  <body>

<div >
  <img class="leftdecoration" src="{% static 'users/images/Asset212x.png' %}" alt="leftdecoration">
  <img src="" alt="">

</div>






    <div >
        <form class="form"   method="POST">
                {% csrf_token %}
                {{ form.password2.errors }}
                {{ form.password1.errors }}
                {{ form.username.errors }}
                {{ form.first_name }}
                {{ form.last_name }}
                <br>
                {{ form.email }}
                <br>
                {{ form.username }}
                <br>
                {{ form.password1 }}
                <br>
                {{ form.password2}}


                <br>
                <button type="submit" name="button" >Register</button>




        </form>

    </div>



  </body>
</html>

NewDjango/users/templates/users/user_register.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Register</title>
    <link rel="stylesheet" href="{% static 'users/register.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">



  </head>
  <body>

<div >
  <img class="leftdecoration" src="{% static 'users/images/Asset212x.png' %}" alt="leftdecoration">
  <img src="" alt="">

</div>






    <div >
        <form class="form"   method="POST">
                {% csrf_token %}
                {{ form.password2.errors }}
                {{ form.password1.errors }}
                {{ form.username.errors }}
                {{ form.first_name }}
                {{ form.last_name }}
                <br>
                {{ form.email }}
                <br>
                {{ form.username }}
                <br>
                {{ form.password1 }}
                <br>
                {{ form.password2}}


                <br>
                <button type="submit" name="button" >Register</button>




        </form>

    </div>



  </body>
</html>